apiVersion: skaffold/v2beta27
kind: Config
build:
  tagPolicy:
    customTemplate:
      template: "{{.GIT_COMMIT}}-{{.VARIANT}}"
      components:
      - name: GIT_COMMIT
        gitCommit: {}
      - name: VARIANT
        envTemplate:
          template: "{{.VARIANT}}"


####  Main  ####################################################################

profiles:
- name: main
  build:
    artifacts:
    - image: microbs-ecommerce-api-gateway
      docker:
        dockerfile: ./services/api-gateway/Dockerfile
    - image: microbs-ecommerce-cart
      docker:
        dockerfile: ./services/cart/Dockerfile
    - image: microbs-ecommerce-checkout
      docker:
        dockerfile: ./services/checkout/Dockerfile
    - image: microbs-ecommerce-cart-data
      docker:
        dockerfile: ./services/cart-data/Dockerfile
    - image: microbs-ecommerce-content
      docker:
        dockerfile: ./services/content/Dockerfile
    - image: microbs-ecommerce-payment
      docker:
        dockerfile: ./services/payment/Dockerfile
    - image: microbs-ecommerce-product
      docker:
        dockerfile: ./services/product/Dockerfile
    - image: microbs-ecommerce-product-data
      docker:
        dockerfile: ./services/product-data/Dockerfile
    - image: microbs-ecommerce-session-data
      docker:
        dockerfile: ./services/session-data/Dockerfile
    - image: microbs-ecommerce-synthetics
      docker:
        dockerfile: ./services/synthetics/Dockerfile
    - image: microbs-ecommerce-web-gateway
      docker:
        dockerfile: ./services/web-gateway/Dockerfile
  deploy:
    kubectl:
      manifests:
      - ./services/*/k8s/*.yaml


####  Variants  ################################################################

- name: basic-bug
  build:
    artifacts:
    - image: microbs-ecommerce-product
      context: ./apps/ecommerce
      docker:
        dockerfile: ./variants/basic-bug/product/Dockerfile
  deploy:
    kubectl:
      manifests:
      - ./variants/basic-bug/*/k8s/*.yaml

- name: bind-localhost
  build:
    artifacts:
    - image: microbs-ecommerce-api-gateway
      context: ./apps/ecommerce
      docker:
        dockerfile: ./variants/bind-localhost/api-gateway/Dockerfile
  deploy:
    kubectl:
      manifests:
      - ./variants/bind-localhost/*/k8s/*.yaml

- name: traffic-spike
  deploy:
    kubectl:
      manifests:
      - ./variants/traffic-spike/*/k8s/*.yaml
